### PR TITLE
Hackathons page styling

### PR DESCRIPTION
**Pull request by JameaKidrick**

### CODE REVIEW

**Review by TojiDevs — DISMISSED** [review]
Looks like the styling matches the UX design files.

Will need to remove commented code.

Will need to make GET requests for updating number data, rather than hard coding.

The search functionality needs to remove the DOM manipulation, this is older code that was resolved yesterday.

**Review by ghost — CHANGES_REQUESTED** [review]
Looks like the styling matches the UX design files. 

Will need to remove commented code. 

Will need to make GET requests for updating number data, rather than hard coding. 

The search functionality needs to remove the DOM manipulation, this is older code that was resolved yesterday.

**Review by TojiDevs — APPROVED** [review]
Made a few changes through git gui, Removed some console.log's and zombie code, Looks good!

**Review by ghost — APPROVED** [review]
Comments and DOM manipulation have been removed, looks good overall. 

Will need to discuss the hard coded values for hackathon/user data.

**Pull request merged**
